server:
  port: 8090

spring:
  thymeleaf:
    check-template: true
    check-template-location: true
    enabled: true
    suffix: .html
  application:
    name: school
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/school
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver